apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: myrc1
spec:
  replicas: 1
  selector:
   matchExpressions:
   -{ key: dc, operator: In, values: [ south ] }
   -{ key: region, operator: IN, Values: [IN]}
   matchLabels:
       app: web   
   dc: IN
  template:
    metadata:
      name: "mypod"
      labels:
        dc: south
        region: In
        app: web
    
    spec:
      Containers:
      - name: "myc1"
        image: "ubuntu"